## Data Structures

### Asset

- Include Asset Update
- sys - System Attributes
    - id: nyancat - Identifier
    - type: Asset - Type of Resource
    - space (Space Link)
    - Include Resource Metadata

### Asset Update

- fields - Field Values
    - title: Nyan Cat
    - file
          - contentType: image/png
          - fileName: Nyan_cat_250px_frame.png
          - url: //images.contentful.com/<space_id>/4gp6taAwW4CmSgumq2ekUm/9da0cd1936871b8d72343e895a00d611/Nyan_cat_250px_frame.png
          - details
              - image
                - width: 250 (number)
                - height: 250 (number)
              - size: 12273 (number)

### Content Type

- fields (array) - Fields
    - (object)
        - id: productName
        - name: Product name
        - type: Text
        - required: true (boolean)
        - localized: false (boolean)
    - (object)
        - id: slug
        - name: Slug
        - type: Symbol
        - required: false (boolean)
        - localized: false (boolean)
    - (object)
        - id: productDescription
        - name: Description
        - type: Text
        - required: false (boolean)
        - localized: false (boolean)
    - (object)
        - id: sizetypecolor
        - name: Size/Type/Color
        - type: Symbol
        - required: false (boolean)
        - localized: false (boolean)
    - (object)
        - id: image
        - name: Image
        - type: Array
        - required: false (boolean)
        - localized: false (boolean)
        - `items`
          - type: Link
          - linkType: Asset
    - (object)
        - id: tags
        - name: Tags
        - type: Array
        - required: false (boolean)
        - localized: false (boolean)
        - `items`
          - type: Symbol
    - (object)
        - id: categories
        - name: Categories
        - type: Array
        - required: false (boolean)
        - localized: false (boolean)
        - `items`
          - type: Link
          - validations
            - linkContentType: 6XwpTaSiiI2Ak2Ww0oi6qa
          - linkType: Entry
    - (object)
        - id: price
        - name: Price
        - type: Number
        - required: false (boolean)
        - localized: false (boolean)
        - disabled: true (boolean)
    - (object)
        - id: brand
        - name: Brand
        - type: Link
        - required: false (boolean)
        - localized: false (boolean)
        - linkType: Entry
    - (object)
        - id: quantity
        - name: Quantity
        - type: Integer
        - required: false (boolean)
        - localized: false (boolean)
    - (object)
        - id: sku
        - name: SKU
        - type: Symbol
        - required: false (boolean)
        - localized: false (boolean)
    - (object)
        - id: website
        - name: Available at
        - type: Symbol
        - required: false (boolean)
        - localized: false (boolean)
- sys
    - space (Space Link)
    - type: ContentType
    - id: 2PqfXUJwE8qSYKuM0U6w8M
    - Include Resource Metadata
- name: Product
- displayField: productName

### Content Type Link
- sys
    - type: Link - Type of Resource
    - linkType: ContentType - Type of linked Resources
    - id: hfM9RCJIk0wIm06WkEOQY - Identifier of Resource

### Empty Array

- sys - System Attributes
    - type: Array - Type of Resource
- total: 0 (number) - Total number of resources matching
- skip: 0 (number) - Number of resources skipped
- limit: 100 (number) - Maximum number of resources in this response
- items (array) - Resources contained in the array

### Entry

- Include Entry Update
- sys - System Attributes
    - id: <entry_id> - Identifier of Resource
    - type: Entry - Type of Resource
    - version: 1 (number) - Version of Resource
    - space (Space Link)
    - contentType (Content Type Link)
    - Include Resource Metadata

### Entry Update

- fields - Localized field values
    - title
        - `en-US`: `Hello, World!`
    - body
        - `en-US`: Bacon is healthy!

### Resource Metadata

- createdAt: `2016-12-20T10:43:35.772Z` - Creation date
- updatedAt: `2016-12-20T10:43:35.772Z` - Date/time of last update
- revision: 1 (number)

### Space Link
- sys - System Attributes
    - type: Link - Type of Resource
    - linkType: Space - Type of linked resources
    - id: <space_id> - Identifier of Resource

### Selected Entry Properties
- fields
    - sys
        - id: entry_1
    - sys
        - id: entry_2

### Select operator example
- sys - System Attributes
    - type: Array - Type of Resource
- total: 1 (number) - Total number of resources matching
- skip: 0 (number) - Number of resources skipped
- limit: 100 (number) - Maximum number of resources in this response
- items (array[Selected Entry Properties]) - Resources contained in the array
