# Group Synchronization

The Sync API allows you to keep a local copy of all content in a space up-to-date via delta updates (only the content that has changed).

## Syncing specific content

By default a sync request response includes all resource types including assets, entries of all content types and deleted resources.

To sync specific content you can specify a `type` parameter for the initial sync:


Parameter        |Description
-----------------|--------------------------------|
all (default)    |Include all new and changed content, i.e., assets, entries and deletions.
`Asset`          |Only include new and changed assets.
`Entry`          |Only include new and changed entries.
`Deletion`       |Only include deletions of assets and entries.
`DeletedAsset`   |Only include deletions of assets.
`DeletedEntry`   |Only include deletions of entries.



## Initial synchronization [/spaces/{space_id}/sync?access_token={access_token}&initial=true&type={type}]

A client syncs content by using the sync endpoint. A single sync consists of one or more pages, each a separate request and response.

The first time a client synchronizes content it sends a request to the sync endpoint with the URI query parameter `initial` set to `true`.

You should only sync with `initial=true` for the initial sync when a client has no existing content. This transfers all content from a space, but **does not** contain content deleted from fields or deleted assets and content entries.

+ Parameters
    + space_id : `<space_id>` (required, string) - Alphanumeric `id` of the Space to retrieve.
    + access_token : `<access_token>` (required, string) - :[token description](tokentype)
    + type : `Deletion` (optional, string) - The type of Resource to sync.

### Query entries [GET]

+ Response 200 (application/vnd.contentful.delivery.v1+json)

  + Attributes (Empty Array)

## Initial synchronization of entries of a specific content type [/spaces/{space_id}/sync?access_token={access_token}&initial=true&type=Entry&content_type={content_type}]

For entries, you can also specify a `content_type` parameter. When specifying `content_type` you must specify `type` as `Entry` (meaning there will be no deletions). You can only specify the `type` and `content_type` parameter at the initial sync along with the `initial` parameter. Any subsequent syncs will only include the types you have specified. If you want to sync entries by content type you should separately subscribe to a `Deletion` or `DeletedEntry` sync to be notified when entries are deleted.

+ Parameters
    + space_id : `<space_id>` (required, string) - Alphanumeric `id` of the Space to retrieve.
    + access_token : `<access_token>` (required, string) - :[token description](tokentype)
    + content_type : `<product_content_type_id>` (required, string) - Alphanumeric `id` of the Content Type to retrieve.

### Query entries [GET]

+ Response 200 (application/vnd.contentful.delivery.v1+json)

  + Attributes (Empty Array)

## Pagination and subsequent syncs [/spaces/{space_id}/sync?access_token={access_token}&sync_token={sync_token}]

Synchronization responses contain either a `nextPageUrl` or `nextSyncUrl` attribute. If there is more content for the current sync, `nextPageUrl` will contain an URL with a `sync_token` which will retrieve the next page. This continues until you have retrieved all content.

At this point, the response will contain a `nextSyncUrl` which you use to make requests in the future and retrieve delta updates between the current content on Contentful and what you retrieved with your last sync request. Upon completion, you will receive a new `nextSyncUrl` which you can again use for future updates.

If a client loses the `nextSyncUrl`, the client should delete its local content and perform an initial synchronization again.

+ Parameters
    + space_id : `<space_id>` (required, string) - Alphanumeric `id` of the Space to retrieve.
    + access_token : `<access_token>` (required, string) - :[token description](tokentype)
    + sync_token : `<sync_token>` (required, string) - An opaque token which is used to identify your previous sync.

### Query entries [GET]

+ Response 200 (application/vnd.contentful.delivery.v1+json)

  + Attributes (Empty Array)
