### Snapshot

- snapshot
  - Include Entry Update
- sys
  - space (Space Link)
  - type: Snapshot
  - id: cat
  - createdBy (User B)
  - createdAt: `2015-05-18T11:29:46.809Z`
  - snapshotType: 'publish'

### Editor Interface

- controls (array[Control], required) - An array of Controls

### Complete Editor Interface

- sys (object)
  - id: default (string)
  - type: Editor Interface (string)
  - contentType (Content Type Link)
- Include Editor Interface

### Control

- widgetId: singleLine (string, required) - A Widget identifier
- fieldId: name (string, required) - A Content Type field identifier
- settings (object) - A set of optional control settings
