### Editing Interface

- controls (array[Control], required) - An array of Controls

### Complete Editing Interface

- sys (object)
  - id: default (string)
  - type: Editor Interface (string)
  - contentType (Content Type Link)
- Include Editing Interface

### Control

- widgetId: singleLine (string, required) - A Widget identifier
- fieldId: name (string, required) - A Content Type field identifier
- settings (object) - A set of optional control settings

