# Group Editing Interface

Editing interfaces represent the look and feel of Content Type fields in the UI. They are tightly
coupled to a specific Content Type and define which Widget has to be rendered for the Content Type's
fields.

__Example__

Let's consider the following Content Type which describes a typical blog post kind of data structure.
It has a title, a body and a category that can be either "General", "iOS" or "Android".

```json
{
  "fields": [
    { "id": "title", "name": "Title", "type": "Symbol" },
    { "id": "body", "name": "Body", "type": "Text" },
    {
      "id": "category", "name": "Category", "type": "Symbol",
      "validations": [{ "in": ["General", "iOS", "Android"] }]
    }
  ]
}
```

An Editing Interface can for example define that the `title` field should be rendered as a normal
input field (the respective widget's id is `singleLine`). Furthermore it can define that the `body`
should be a normal textarea (= `multipleLine`) and also that the `category` should be rendered as a
dropdown field (= `dropdown`).

The Editing Interface would look like this:

```json
{
  "controls": [
    { "fieldId": "title", "widgetId": "singleLine" },
    { "fieldId": "body", "widgetId": "multipleLine" },
    { "fieldId": "category", "widgetId": "dropdown" }
  ]
}
```

Please note that there are specific sets of applicable Widgets per Content Type field type:

| Widget ID               | Applicable field types                 | Description               | Possible settings                                                                                                    |
|-------------------------|----------------------------------------|---------------------------|----------------------------------------------------------------------------------------------------------------------|
| assetLinkEditor         | Asset                                  |                           |                                                                                                                      |
| assetGalleryEditor      | Asset (Array)                          |                           |                                                                                                                      |
| assetLinksEditor        | Asset (Array)                          |                           |                                                                                                                      |
| boolean                 | Boolean                                |                           | trueLabel (default: "Yes") - True condition custom label falseLabel (default: "No") - False condition custom label   |
| datePicker              | Date                                   |                           | format (Default: timeZ, values: [dateonly, time, timeZ]) - Format ampm (Default: '24', values: [12, 24]) - Time Mode |
| entryCardEditor         | Entry                                  |                           |                                                                                                                      |
| entryCardsEditor        | Entry (Array)                          |                           |                                                                                                                      |
| entryLinkEditor         | Entry                                  |                           |                                                                                                                      |
| entryLinksEditor        | Entry (Array)                          |                           |                                                                                                                      |
| fileEditor              | File                                   |                           |                                                                                                                      |
| numberEditor            | Integer, Number                        |                           |                                                                                                                      |
| rating                  | Integer, Number                        |                           | stars (default: 5, range: 1-20) - Number of stars                                                                    |
| locationEditor          | Location                               |                           |                                                                                                                      |
| objectEditor            | Object                                 |                           |                                                                                                                      |
| urlEditor               | Symbol                                 |                           |                                                                                                                      |
| slugEditor              | Symbol                                 |                           |                                                                                                                      |
| ooyalaEditor            | Symbol                                 |                           |                                                                                                                      |
| ooyalaMultiAssetEditor  | Symbol (Array)                         |                           |                                                                                                                      |
| kalturaEditor           | Symbol                                 |                           |                                                                                                                      |
| kalturaMultiVideoEditor | Symbol (Array)                         |                           |                                                                                                                      |
| listInput               | Symbol (Array)                         |                           |                                                                                                                      |
| multipleLine            | Text                                   |                           |                                                                                                                      |
| markdown                | Text                                   |                           |                                                                                                                      |
| singleLine              | Text, Symbol                           | A simple text input field |                                                                                                                      |
| dropdown                | Text, Symbol, Integer, Number, Boolean |                           |                                                                                                                      |
| radio                   | Text, Symbol, Integer, Number          |                           |                                                                                                                      |

## Editing Interface [/spaces/{space_id}/content_types/{content_type_id}/editor_interfaces/{editor_interface_id}]

While it is theoretically possible to create more than one Editing Interface
(by using different IDs) the UI will only ever read and use the Editing Interface with the ID `default`.

__Limitations__

Since Editing Interfaces are describing Content Type fields, they are tightly coupled to the Content Type field's IDs. Please note
that there is currently no automatic synchonization in the API between a Content Type and an Editing Interface. This means that an
Editing Interface might get out of sync when you rename a Content Type's field. In that case you will have to file an update of the
respective Editing Interface as well.

+ Parameters
    + space_id: 5smsq22uwt4m (required, string) - ID of the Space in form of a string
    + content_type_id: 3ORKIAOaJqQWWg86MWkyOs (required, string) - ID of the Content Type in form of a string
    + editor_interface_id: default (required, string) -  ID of the Editor Interface in form of a string

### Create/Update an Editing Interface [PUT]

This endpoint can be used to create a new Editing Interface with an ID specified by the user, or to update a specific Editing Interface via its ID.

Note that when updating an existing Editing Interface, you always need to specify the last version you got of the Editing Interface you are updating with `X-Contentful-Version`.

+ Request Create new Editing Interface with a predefined identifier
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Editing Interface)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Editing Interface)

### Get a single Editing Interface [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Editing Interface)




