## Common Resource Attributes

Every resource returned by the API will have a `sys` property, which is an object containing system managed metadata. The exact metadata available depends on the type of the resource, but at minimum the `sys.type` property is defined.

Note that none of the `sys` fields are editable and only the `sys.id` field can be specified in the creation of an item (as long as it is not a Space).

The `sys.id` property will be defined for every resource that is not a collection. For example, a `Space` resource will have a `sys.type` and `sys.id`:

```
{
  "sys": {
    "type": "Space",
    "id": "cfexampleapi"
  }
}
```

Field               |Type          |Description                                |Applies to
--------------------|--------------|-----------------------------------------  |-----------------------------
sys.type            |String        |Type of resource.                          |All
sys.id              |String        |Unique ID of resource.                     |All except arrays
sys.space           |Link          |Link to resource's space.                  |Entries, assets, content types
sys.contentType     |Link          |Link to entry's content type.              |Entries
sys.publishedCounter|Integer       |Number of times resource was published.    |Entries, assets, content types
sys.publishedVersion|Integer       |Published version of resource.             |Entries, assets, content types
sys.version         |Integer       |Current version of resource.               |Entries, assets, content types
sys.firstPublishedAt|Date          |Time resource was first published.         |Entries, assets, content types
sys.createdAt       |Date          |Time resource was created.                 |Entries, assets, content types
sys.createdBy       |Link          |Link to creating user.                     |Entries, assets, content types
sys.publishedAt     |Date          |Time resource was published.               |Entries, assets, content types
sys.publishedBy     |Link          |Link to publishing user.                   |Entries, assets, content types
sys.updatedAt       |Date          |Time resource was updated.                 |Entries, assets, content types
sys.updatedBy       |Link          |Link to updating user.                     |Entries, assets, content types

:[Collection Resources and Pagination](../collections-and-pagination.md)
