## Common resource attributes

Every resource returned by the :[API name](apiname) will have a `sys` property, which is an object containing system managed metadata. The exact metadata available depends on the resource type, but at minimum it defines the `sys.type` property.

**Note**: None of the `sys` fields are editable and you can only specify the `sys.id` in the creation of an item (If it's not a _space_).

Contentful defines the `sys.id` property for every resource that is not a collection. For example, a `Space` resource will have a `sys.type` and `sys.id`:

```json
{
  "sys": {
    "type": "Space",
    "id": "cfexampleapi"
  }
}
```

Field          |Type          |Description                     |Applies to
---------------|--------------|--------------------------------|-----------------------------
sys.type       |String        |Resource type.               |All
sys.id         |String        |Unique ID of resource.          |All except arrays
sys.space      |Link          |Link to resource's space.       |Entries, assets, content types
sys.contentType|Link          |Link to entry's content type.   |Entries
sys.revision   |Integer       |Published version of resource. |Entries, assets, content types
sys.createdAt  |Date          |Time resource was created.      |Entries, assets, content types
sys.updatedAt  |Date          |Time resource was updated.      |Entries, assets, content types
sys.locale     |String        |Locale of the resource.         |Entries and assets

**Note**: the `revision` field refers to the current number of revisions of an entry published. [Find out more in the Content Management API documentation.](https://www.contentful.com/docs/references/content-management-api/#/introduction/collection-resources-and-pagination)

:[Collection Resources and Pagination](../collections-and-pagination.md)
