FORMAT: 1A
HOST: https://cdn.contentful.com

# Contentful Delivery API

The Contentful Delivery API is a _fast_ read-only API for retrieving your content from Contentful. It is powered by our global CDN so you get the benefits of our content-aware caching and  

## Common Resource Attributes

Every resource returned by the Content Delivery API will have a `sys` property, which is an object containing system managed metadata. The exact metadata available depends on the type of the resource, but at minimum the `sys.type` property should be defined. The `sys.id` property will be defined for every resource that is not a collection. For example, a `Space` resource will have a `sys.type` and `sys.id`:

```json
{
  "sys": {
    "type": "Space",
    "id": "cfexampleapi"
  }
}
```

Further `sys` properties such as `sys.createdAt` and `sys.revision` can be seen in the examples for those resources that support them.

## Collection Resources & Pagination

Collections of resources are returned in a wrapper object that contains additional information useful for pagination over large result sets:

```json
{
  "sys": { "type": "Array" },
  "skip": 0,
  "limit": 100,
  "total": 1256,
  "items": [ /* 100 individual resources */ ]
}
```

In the above example, a client would get the next 100 resources by repeating their request with the `skip` query parameter set to `100`.
Keep in mind that you should define a field to order by when paging through result sets. such as `order=sys.createdAt` when you plan to page through many results).


# Group Spaces

All content in Contentful belongs to a _Space_. You can think of spaces like databases, you will generally have at least one space for a project, but may opt to use a separate space for e.g. testing. 

## Space [/spaces/{space_id}{?access_token}]

Each space has a name, a set of locales, and some system metadata.

+ Parameters
    + space_id (required, string, `cfexampleapi`) ... Alphanumeric `id` of the Space to retrieve.
    + access_token (required, string, `b4c0n73n7fu1`) ... A *production* Content Delivery API Key.


+ Model (application/vnd.contentful.delivery.v1+json)

        {
          "sys": {
            "type": "Space",
            "id": "cfexampleapi"
          },
          "name": "Contentful Example API",
          "locales": [
            {
              "code": "en-US",
              "default": true,
              "name": "English"
            },
            {
              "code": "tlh",
              "default": false,
              "name": "Klingon"
            }
          ]
        }

### Get a Space [GET]

+ Request

    + Headers

            Authorization: Bearer {access_token}

+ Response 200
    
    [Space][]

# Group Entries

Entries are the documents contained within a space. They might represent blog posts or events or anything else that you have defined a [Content Type](#content-types) for.

## Entries [/spaces/{space_id}/entries{?access_token}]

+ Parameters
    + space_id (required, string, `cfexampleapi`) ... Alphanumeric `id` of the Space to retrieve.
    + access_token (required, string, `b4c0n73n7fu1`) ... A *production* Content Delivery API Key.

+ Model (application/vnd.contentful.delivery.v1+json)

        {
          "sys": {
            "type": "Array"
          },
          "skip": 0,
          "limit": 100,
          "total": 1234,
          "items": [ ]
        }
        

### Query Entries [GET]

+ Response 200

    [Entries][]

    



