FORMAT: 1A
HOST: https://api.contentful.com

# Content Management API
The Content Management API is a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API for managing content.

In Contentful content is represented as Entries and Assets divided into Spaces. Apps and websites depend on the structure of Entries, so every Entry must comply to a specific Content Type. Assets represent binary files like images, videos and other media.

Entries are represented as JSON data; Assets are represented as (binary) files.

The API can be securely accessed via HTTPS and will only be available to clients authenticating with an access token.

Managing content via an API has many benefits:

- Custom applications can use the API to manage content.
- Scripts can use the API to automate various tasks.
- Contentful's own content management web app is a user-friendly JavaScript application which is solely based on the API.

If you want to deliver content (e.g. to the web or to mobile apps) use the Content Delivery API. The Content Management API is meant to be used only for managing content, not delivering it. For example, you shouldn't use the Content Management API to display blog posts on a web site or pull information into a mobile web app unless that app is meant for editing content.

Conceptual documentation, as well as further resources like tutorials and libraries can be found on [our Developer Center](https://contentful.com/developers/documentation/).
