FORMAT: 1A
HOST: https://api.contentful.com

# Content Management API
Contentful's Content Management API is a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API for managing content.

In Contentful content is represented as entries and assets divided into spaces. Apps and websites depend on the structure of entries, so every entry must comply to a specific content type. Assets represent binary files like images, videos and other media.

Entries are represented as JSON data; assets are represented as (binary) files.

The API can be securely accessed via HTTPS and will only be available to clients authenticating with an access token.

Managing content via an API has many benefits:

- Custom applications can use the API to manage content.
- Scripts can use the API to automate various tasks.
- The Contentful web app is a user-friendly JavaScript application which is solely based on the API.

If you want to deliver content (e.g. to the web or to mobile apps), you should use the Content Delivery API. Whereas the Content Management API may be used to deliver and manage content within an application, it shouldn't be used to massively deliver content to end users. For example, you shouldn't use the Content Management API to display blog posts on a web site or pull information into a mobile web app unless that app is meant for editing content.

Note that the structure of responses of the Content Management API differs from those of the Content Delivery API. GET responses from the Content Management API retrieve the entirety of items (i.e. includes all localized or even unpublished content).

Conceptual documentation, as well as further resources like tutorials and libraries can be found in the [developer center](https://contentful.com/developers/documentation/).

## Authentication

Learn about authenticating to the Content Management API and obtain your access token in the [developer center](http://www.contentful.com/developers/docs/references/authentication/#the-management-api).

## Resource IDs

When creating a resource you may either chose an ID or let the server generate a random ID for you.

When choosing an ID yourself it must adhere to the following rules:

- Length must be between 1 and 64 characters
- May consist of alphanumeric characters, minus `-`, underscore `_` and period `.`

In terms of a regular expression: `/^[a-zA-Z0-9-_.]{1,64}$/`.

## Updating resources

When updating an existing resource don't only pass the changes you made; Instead pass the entire resource including the changes you've made. In other words: Do not pass a subset of properties and expect some kind of merge to occur. If you update with only a subset of properties all existing properties which are not part of that update will be gone.

To summarize, resources should always be updated like this:

- Fetch current resource
- Make changes to current resource
- Update resource by passing changed resource along with current version number

This way no unseen changes are ever overridden and unexpected conflicts are unlikely to occur.

Be aware that none of the `sys` property fields can be updated, including `sys.id`.

## Updating and version locking

Contentful uses optimistic locking. When updating an existing resource its current version needs to be specified as the value of the `X-Contentful-Version` HTTP header (this header is automatically set when using our [official SDKs][sdks]). The version is compared with the resource's current version on the server to ensure that a client doesn't overwrite a resource that has since been updated. If the version changed in between the update will be rejected.

[sdks]: https://www.contentful.com/developers/docs/code/libraries/

## API rate limits

The Content Management API enforces standard rate limits per hour and per second. The limits exist to prevent unlimited usage and ensure the consumption of resources that a single account can exercise is limited. Rate limits are set to 18000 requests per hour and 10 requests per second.

The rate limits are implemented through a standard mechanism of the HTTP protocol (returning response code 429).

Contentful uses HTTP headers to inform users how they're rate limited, what their rate limits are and when they can make their next request.

Header                                    | Status Code   | Description
------------------------------------------|---------------|----------------------------------------------------
`X-Contentful-RateLimit-Hour-Limit`       | All requests. | The hourly rate limit.
`X-Contentful-RateLimit-Hour-Remaining`   | All requests. | The number of requests remaining before the hourly rate limits are enforced.
`X-Contentful-RateLimit-Second-Limit`     | All requests. | The per second rate limit.
`X-Contentful-RateLimit-Second-Remaining` | All requests. | The number of requests remaining before the per second rate limits are enforced.
`X-Contentful-RateLimit-Reset`            | All requests. | The number of seconds until the next request can be made.

It's important to note that the `X-Contentful-RateLimit-Reset` header does _not_ return the time until the next full reset. Instead it tells you when the next request can be made. If a per second rate limit is enforced it will return `1` (time until the next second). If an hourly rate limit is enforced it will return the time until the next sliding window. If no limits are enforced it returns `0` because the next request can be made immediately.

:[Common Resource Attribute](_partials/cma/resource-attributes.apib)

## Errors

:[Common errors](_partials/errors-common.md)

### Management API error types

HTTP Status Code   |Error Code       |Description
-------------------|-----------------|----------------------------------------------------------------------------------
`409`|`VersionMismatchError`|This error happens when you're trying to update an existing asset, entry or content type, and you either didn't specify the current version of the object or specify an outdated version.
`422`|`ValidationFailedError`|The request payload was a valid JSON, but something was wrong with the data. Check the error details field – it should provide more specific information about the error.
`422`|`InvalidEntryError`|The entered value is invalid.
`422`|`ValidationFailedError`|The triggered query references an invalid field.

## HTTP details

Learn more in the [developer center](https://www.contentful.com/developers/docs/references/http-details/).

## API versioning

All API requests should specify a `Content-Type` header of `application/vnd.contentful.management.v1+json`.

Otherwise, we will automatically route your request to the latest version of the API.
This could break clients which expect the outdated API version.
To be on the safe side, always specify the `Content-Type` header.

# Group Spaces

## Spaces collection [/spaces]

Spaces are containers for content types, entries and assets and other resources. API consumers, like mobile apps or websites, typically fetch data by getting entries and assets from one or more spaces.

In Contentful you can be a member of multiple organizations.

Depending on your role in the organization you can create spaces in them or not: Only organization owners and admins have this permission.

When you sign up the first time, you'll create a new organization. When you're invited to an existing organization, you'll become a member of it.

If you only have a single organization, any space you create will be automatically associated with that organization.

However, if you're an admin or an owner in multiple organizations you need to pass the ID of the organization you want to create the space in.

### Create a space [POST]

The `X-Contentful-Organization` header is optional if an account only belongs to one organization.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Organization: 1PLOOEmTI2S1NYald2TemO

    + Attributes
        - name: Example Space - Name of the Space
        - defaultLocale: en-US - Default locale of the Space

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Space)

### Get all spaces an account has access to [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

## Space [/spaces/{space_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string

### Update a space [PUT]

The `X-Contentful-Organization` header is optional if an account only belongs to one organization.

+ Request Update existing
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Version: 1

    + Attributes
        - name: Hyper Space - Name of the Space

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Space)

### Get a space [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Space)

### Delete a space [DELETE]

Delete an existing space by doing a DELETE request to `/spaces/ID`. Note that deleting a space will remove its entire content, including all content types, entries and assets. Be careful as this action can not be undone.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 204 (application/vnd.contentful.management.v1+json)

# Group Content types

:[What is a Content Type?](_partials/content-types-description.md)

## Content type collection [/spaces/{space_id}/content_types]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string

### Get all content types of a space [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

### Create a content type [POST]

**Creating content types with `POST` is strongly discouraged!**

When using this endpoint, an ID will be automatically generated for the created content type and returned on the response.

In contrast, using the `PUT` method below allows you to control the ID of the created content type. This is especially important for content type IDs because they are often used as parameters in your own code. It's much nicer to query for  `content_type=newsArticle` than `content_type=hs7Kj10al3b6x`.

Finally, in these responses, you can also specify validations and determine whether a field should be required or localized.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Content Type Creation)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type)


## Content type [/spaces/{space_id}/content_types/{content_type_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string
    + content_type_id: 3ORKIAOaJqQWWg86MWkyOs (required, string) - ID of the Content Type in form of a string

### Create/update a content type [PUT]

This endpoint can be used to create a new content type with an ID specified by the user, or to update a specific content type via its ID.

Note that when updating an existing content type, you always need to specify the last version you got of the content type you are updating with `X-Contentful-Version`.

__Validations__

Whenever you are creating or updating a content type you can add or remove validations to the fields present in the content type schema. Validations, specified in the validations property a field, are included in the payload sent to the server when you create or update a content type.

Validation      |Description                              |Applicable to|Example                         |
----------------|-----------------------------------------|-------------|--------------------------------|
`linkContentType`|Takes an array of content type ids and validates that the link points to an entry of that content type.|Links to entries|`{"linkContentType": ["post","doc","product"]}`
`in`|Takes an array of values and validates that the field value is in this array.|Text, Symbol, Integer, Number| `{"in": ["General", "iOS", "Android"]}`
`linkMimetypeGroup`|Takes a MIME type group name and validates that the link points to an asset of this group.|Links to assets|`{"linkMimetypeGroup": "image"}`
`size`|Takes optional min and max parameters and validates the size of the array (number of objects in it).|Arrays, Text, Symbol|`{"size": { "min": 5, "max": 20}}`
`range`|Takes optional min and max parameters and validates the range of a value.|Number, Integer|`{"range": { "min": 5, "max": 20}}`
`regexp`|Takes a string that reflects a JS regex and flags, validates against a string. See [JS reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) for the parameters.|Text, Symbol|`{"regexp": {"pattern": "^such", "flags": "im"}}`

Please notice that validations will only take effect after the content type has been activated and that previously existing entries will not be validated until they are published again.

To remove a specific validation, update the content type leaving that validation out of the field's validations collection. To remove all the validations applied to a field update the content type schema removing the validations property.

__Field IDs__

It is possible to change the ID of a content type's field in the Contentful Web App. Please note, that the API will return different data afterwards and that this might break your currently existing code base.

__Omitting Fields__

If you have fields in your content type and entries, which you don't want to distribute to end users (eg. workflow states), you can omit fields from the CDA and CPA responses.
To do so, update the content type with the `omitted` property set to `true` in the chosen field and activate it.
From then on, it will still be available as part of the CMA responses and the Web App but skipped in the CDA and CPA.
To revert this, repeat this but with `omitted` set to `false`.

__Deleting Fields__

Sometimes you may want to permanently delete certain content type fields and all the related data in the entries, for example to remove legacy data that is no longer needed.
In order to accomplish this, the first step is to omit the field you're targeting for deletion and activate the content type.
We made this step mandatory in order to avoid accidental data loss. You can first try out whether your client applications can handle the deletion correctly and have a quick and easy way to revert that change.
Once you have confirmed that you are safe to delete the field, you can proceed to update your content type either with the corresponding field left out of the payload, or with a `deleted` property set to `true` on the content type field you intend to delete. The deletion becomes final after you once again activate the content type. This action is permanent and cannot be undone.
After this, you will not receive this field as part of any API response anymore and your limit of 50 fields per content type is reduced by 1.

+ Request Create new Content Type with a predefined identifier
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Content Type Creation)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type)

+ Request Update existing Content Type
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Version: 14

    + Attributes (Content Type Creation)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type Update)

+ Request Update existing Content Type with validations
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Version: 15

    + Attributes (Content Type Validations)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type Update)

+ Request Update an existing Field's identifier
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Version: 16

    + Attributes (Content Type Update Field ID)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type Update)

### Get a single content type [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type)

### Delete a content type [DELETE]

Before you can delete a content type you need to deactivate it.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 204 (application/vnd.contentful.management.v1+json)

## Content type activation [/spaces/{space_id}/content_types/{content_type_id}/published]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + content_type_id: 3ORKIAOaJqQWWg86MWkyOs (required, string) - ID of the content type in form of a string

### Activate a content type [PUT]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 11

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type Published)

### Deactivate a content type [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Content Type Unpublished)

## Activated content type collection [/spaces/{space_id}/public/content_types]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all activated content types of a space [GET]

Retrieves the activated versions of content types, ignoring any changes made since the last activation.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)


:[Group Editor Interface](_partials/cma/editor-interface.apib)

# Group Entries

## Entries collection [/spaces/{space_id}/entries]

Entries represent textual content in a space. An entry's data adheres to a certain content type.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all entries of a space [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

### Create an entry [POST]

Before you can create an entry you need to create and activate a content type.

When creating a new entry you need to pass the ID of the entry's desired content type as the `X-Contentful-Content-Type` header.

When using this endpoint, an ID will be automatically generated for the created entry and returned on the response.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Content-Type: hfM9RCJIk0wIm06WkEOQY

    + Attributes (Entry Update)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry)

## Entry [/spaces/{space_id}/entries/{entry_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + entry_id: helloworld (required, string) - ID of the entry in form of a string

### Create/update an entry  [PUT]

This endpoint can be used to create a new entry with an ID specified by the user, or to update a specific entry via its ID.

Note that when updating an existing entry, you always need to specify the last version you got of the entry you are updating with `X-Contentful-Version`.

Before you can create an entry you need to create and activate a content type.

When creating a new entry you need to pass the ID of the entry's desired content type as the `X-Contentful-Content-Type` header.

For updating an entry, passing the ID of the entry's content type is not required.

+ Request Create new entry with a predefined identifier
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Content-Type: hfM9RCJIk0wIm06WkEOQY

    + Attributes (Entry Update)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry)

+ Request Update existing entry
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Content-Type: hfM9RCJIk0wIm06WkEOQY
            X-Contentful-Version: 4

    + Attributes (Entry Update)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry)

### Get a single entry [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry)

### Delete an entry [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 4

+ Response 204 (application/vnd.contentful.management.v1+json)

## Entry publishing [/spaces/{space_id}/entries/{entry_id}/published]

After publishing the entry it will be available via the Content Delivery API.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + entry_id: helloworld (required, string) - ID of the entry in form of a string

### Publish an entry [PUT]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 6

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry Published)

### Unpublish an entry [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 7

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry Update)

## Entry archiving [/spaces/{space_id}/entries/{entry_id}/archived]

An entry can only be archived when it's not published.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + entry_id: helloworld (required, string) - ID of the entry in form of a string

### Archive an entry [PUT]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 8

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry Update)

### Unarchive an entry [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 9

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Entry Update)

# Group Assets

## Assets collection [/spaces/{space_id}/assets]

Assets represent files in a space. An asset can be any kind of file: an image, a video, an audio file, a PDF or any other filetype. Assets are usually attached to entries through links.

Assets can optionally be localized by providing separate files for each locale. Those assets which are not localized simply provide a single file under the default locale.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all assets of a space [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

### Create an asset [POST]

When using this endpoint, an ID will be automatically generated for the created asset and returned on the response.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Asset Update)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset)


## Published assets collection [/spaces/{space_id}/public/assets]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string

### Get all published assets of a space [GET]

Retrieves the published versions of assets.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

## Asset [/spaces/{space_id}/assets/{asset_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string
    + asset_id: baconpancakes (required, string) - ID of the Asset in form of a string

### Create/update an asset [PUT]

This endpoint can be used to create a new asset with an ID specified by the user, or to update a specific asset via its ID.

Note that when updating an existing asset, you always need to specify the last version you got of the asset you are updating with `X-Contentful-Version`.

+ Request Create a new asset with a predefined identifier
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Asset Update)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset)

+ Request Update existing asset
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Version: 1

    + Attributes (Asset Update)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset)

### Get a single asset [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset)

### Delete an asset [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 1

+ Response 204 (application/vnd.contentful.management.v1+json)

## Asset processing [/spaces/{space_id}/assets/{asset_id}/files/{locale}/process]

Asset processing happens asynchronously, the call will not block until it has finished.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + asset_id: baconpancakes (required, string) - ID of the asset in form of a string
    + locale: `en-US` (required, string) - Locale for which files should be processed

### Process an asset [PUT]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 1

+ Response 204 (application/vnd.contentful.management.v1+json)

## Asset publishing [/spaces/{space_id}/assets/{asset_id}/published]

After publishing the asset it will be available via the Content Delivery API.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + asset_id: baconpancakes (required, string) - ID of the asset in form of a string

### Publish an asset [PUT]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 13

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset Published)

### Unpublish an asset [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 14

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset)

## Asset archiving [/spaces/{space_id}/assets/{asset_id}/archived]

An asset can only be archived when it's not published.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string
    + asset_id: baconpancakes (required, string) - ID of the Asset in form of a string

### Archive an asset [PUT]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 15

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset)

### Unarchive an asset [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            X-Contentful-Version: 16

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Asset Update)

# Group Locales

Locales allow the definition of translated content for both assets and entries. A locale
consists mainly of a name and a locale code.

## Locale collection [/spaces/{space_key}/locales]

+ Parameters
    + space_key: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all locales of a space [GET]

The locale collection endpoint returns a list of all the created locales. One of those
will have the flag `default` set to true and is the locale that is used if no other
locale was specified for the request (e.g. when reading an entry).

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

+ Response 200 (application/vnd.contentful.management.v1+json)
  + Attributes (Empty Array)

### Create a locale [POST]

Posting a payload to the locale's collection endpoint creates a new locale
for the given space. Please note that you cannot create two locales with
the same locale code.

+ Request
  + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
  + Attributes (Locale)
+ Response 201 (application/vnd.contentful.management.v1+json)
  + Attribute (Locale Complete)

## Locale [/spaces/{space_key}/locales/{locale_id}]

+ Parameters
  + space_key: fp91oelsziea (required, string) - ID of the Space in form of a string
  + locale_id: 1WFZQhacJ9SJvkd7e0d8ys (required, string) - ID of the Locale in form of a string

### Get a locale [GET]

This endpoint returns a single locale with all its metadata.

+ Request
  + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
+ Response 200 (application/vnd.contentful.management.v1+json)
  + Attribute (Locale Complete)

### Update a locale [PUT]

Putting a payload against a single entities endpoint allows an update of a locale.

Please note that renaming a locale changes the responses for upcoming requests, which
might break your existing code.

Finally, it is not possible to change what is the default locale of a space, as these are
permanent entities.

+ Request
  + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
  + Attributes (Locale)
+ Response 201 (application/vnd.contentful.management.v1+json)
  + Attribute (Locale Complete)

### Deleting a locale [DELETE]

This endpoint deletes an existing locale. Please note that it is **not** possible to recover
from this action! Every content that was stored for that specific locale gets deleted and
cannot be recreated by creating the same locale again.

+ Request
  + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
+ Response 204

# Group Search parameters

See the [reference documentation for the Content Delivery API](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters) for a list of search parameters supported for querying resources. Please note that the Content Management API does not support the `include` functionality.

To use search parameters, these should be put in the end of your query, similar to the Content Delivery API (e.g. `https://api.contentful.com/spaces/space_id/entries?content_type=X`).

# Group Webhooks

Webhooks in Contentful can notify you or someone else when content has changed by calling a preconfigured HTTP endpoint. This can be used for notifications, static site generators or other forms of post-processing that is sourced from Contentful.

### When are webhooks called
Webhooks will be called as the result of an action executed against assets, entries or content types. The following table summarizes the actions that Contentful offers for every type:

type/action| Create | Save | Auto save | Archive | Unarchive | Publish | Unpublish | Delete
-----------|--------|------|-----------|---------|-----------|---------|-----------|---------
Content type | Yes   | Yes  | No        | No      | No        | Yes     | Yes       | Yes
Entry      | Yes    | Yes  | Yes       | Yes     | Yes       | Yes     | Yes       | Yes
Asset      | Yes    | Yes  | Yes       | Yes     | Yes       | Yes     | Yes       | Yes

For example:

- A configured webhook could be called for entry creation or asset save.
- A configured webhook won't be called for content type archival because content types can't be archived.

#### Topics
When creating a webhook you have to explicitly specify for which changes on your content (topics) you want your webhook called. Think of it as if you were subscribing your webhook to different event sources. For example, you could decide that a webhook is going to be called when:

- Any content (no matter which type) is published.
- Assets are deleted.
- Anything happens to your entries.

These restrictions have to be translated into a list of `[Type].[Action]` pairs, `[*.publish, Asset.delete, Entry.*]`, and included in the payload that defines the webhook.

`*` is a wildcard character that can be used in place of any action or type. The combination `*.*` is also valid and it means that your webhook will be subscribed to all actions across all types. It's important that you keep in mind that using `*` opens the door for your webhook to be called for future actions or types that didn't exist when the webhook was created or updated.

#### Auto save

The Contentful web app automatically saves the documents you are working on after every change you make. Besides that, Contentful keeps track of those documents that are active in the web app and uses that information to call configured webhooks. For this matter Contentful considers active those documents that had been edited in the last 20 seconds.

This means that, for example, if you are editing an entry in the web app for one minute, and you have a webhook configured to be called for `auto_save` actions, that webhook will be called 3 times.

## Request Format

When content changes all webhooks subscribed to that change are fired. For each webhook a `POST` request will be made to its `url`. The HTTP request has the following headers & request body:

### Headers

Every webhook request will include the following predefined headers:

Header Name                 | Value
----------------------------|--------
`X-Contentful-Topic`        |`ContentManagement.[Type].[Action]`
`X-Contentful-Webhook-Name` | Webhook's name
`Content-Type`              |`application/vnd.contentful.management.v1+json`

Consuming services can use the `X-Contentful-Topic` to determine the type of the payload included in the webhook call without looking into it. Notice that the `Content-Type` header has the `application/vnd.contentful.management.v1+json` value and many web frameworks (such as Express.js) and their middleware components only automatically parse a request body if the content-type header is `application/json`, and thus require additional configuration to parse request bodies with a different content-type header.

Besides the aforementioned headers you can configure your webhooks to be called with a set of additional headers of your choice. When creating or updating a webhook you can provide a list of headers that will be included in successive calls to that webhook.

__example__

Let's assume that:

- One of your entries has just been published.
- The name of your webhook is `Very hook`.
- You have defined two custom headers: `X-Very: wow` and `Authentication: indeed`.

In this scenario your webhook would we called with the following set of headers:

```
X-Contentful-Topic: ContentManagement.Entry.publish
X-Contentful-Webhook-Name: Very hook
X-Very: wow
Authentication: indeed
```

### Body

The payload received by a webhook will change depending on the action type:

- For `Publish` it will receive the latest published version. That's the same payload as the one available through the Delivery API with the exception that the payload for Entries and Assets will contain all locales, e.g. instead of `fields.name` there will be `fields['en-US'].name`.
- For `Unpublish` and `Delete` it will receive a deletion object. In the case of Entries the Deletions are extended with the id of their Content Type.
- For `Auto Save`, `Archive`, `Unarchive` and `Create` it will receive the latest draft version at the time the webhook was triggered. That's the same payload as the one available through the Management API.

__Example__

When an entry has been published:

```json
{
  "sys": {
    "type": "Entry",
    "id": "cat",
    "space": {"sys": {"type": "Link", "linkType": "Space", "id": "example"}},
    "contentType": {"sys": {"type": "Link", "linkType": "ContentType", "id": "cat"}},
    "createdAt": "2013-03-26T00:13:37.123Z",
    "updatedAt": "2013-03-26T00:13:37.123Z",
    "revision": 1
  },
  "fields": {
    "name": {"en-US": "Nyan cat"},
    "color": {"en-US": "Rainbow"},
    "nyan": {"en-US": true},
    "birthday": {"en-US": "2011-04-02T00:00:00.000Z"},
    "diary": {"en-US": "Nyan cat has an epic rainbow trail."},
    "likes": {"en-US": ["rainbows", "fish"]},
    "bestFriend": {"en-US": {"type": "Link", "linkType": "Entry", "id": "happycat"}}
  }
}
```

When an entry has been unpublished:

```json
{
  "sys": {
    "type": "DeletedEntry",
    "id": "cat",
    "space": {"sys": {"type": "Link", "linkType": "Space", "id": "example"}},
    "contentType": {"sys": {"type": "Link", "linkType": "ContentType", "id": "type"}},
    "createdAt": "2013-03-26T00:13:37.123Z",
    "updatedAt": "2013-03-26T00:13:37.123Z",
    "revision": 1
  }
}
```

### Error handling

Contentful will use the HTTP response status code of the webhook call to decide whether it succeeded or failed:

- Success: The webhook responded with an HTTP status code < 300
- Error: The webhook responded with an HTTP status code >= 300

In case of an error, the webhook will periodically retry its request with
increasing delays in between up to a maximum of 3 attempts.

## Webhooks collection [/spaces/{space_id}/webhook_definitions]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all webhooks of a space [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

### Create a webhook [POST]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Webhook attributes)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Definition)

+ Request Create a webhook with custom headers
    This example creates a webhook with custom headers which can be defined by an array of objects
    with `key` and `value` properties. Please note that the keys and values have to follow the
    [RFC 7230 specification](https://tools.ietf.org/html/rfc7230#section-3.2), which means that
    only US-ASCII characters are allowed.

    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Webhook attributes)
        - headers (array) - An object with header key-value pairs
            - (object)
                - key: header1
                - value: value1
            - (object)
                - key: header2
                - value: value2

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Definition)

## Webhook [/spaces/{space_id}/webhook_definitions/{webhook_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + webhook_id: foobar (required, string) - ID of the webhook in form of a string

### Create/update a webhook [PUT]

+ Request Create with a predefined identifier
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Webhook attributes)
        - headers (array) - An object with header key-value pairs
            - (object)
                - key: header1
                - value: value1
            - (object)
                - key: header2

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Definition)

+ Request Update existing
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json
            X-Contentful-Version: 1

    + Attributes (Webhook attributes)
        - headers (array) - An object with header key-value pairs

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Definition)

### Get a single Webhook [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Definition)

### Delete a webhook [DELETE]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 204 (application/vnd.contentful.management.v1+json)


# Group Webhook calls

When setting up and maintaining webhook endpoints, it is often necessary to analyze the exact request and response payloads and headers in order to verify that the setup is correct or to diagnose issues.
To facilitate this process, a number of API endpoints are available that expose this information.

## Webhook call overviews [/spaces/{space_id}/webhooks/{webhook_id}/calls]

The call overviews consist of a list of the most recent webhook calls made, their status, possible errors, and the target URL.

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + webhook_id: foobar (required, string) - ID of the webhook in form of a string

### Get the most recent call overviews [GET]
+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Call Overview Array)


## Webhook call details [/spaces/{space_id}/webhooks/{hook_id}/calls/{call_id}]

The call details provide detailed information about the outgoing request and the response, including headers, body and possible errors.
Request and response body are currently truncated at 500kb and 200kb respectively.

+ Parameters
    + space_id: example (required, string) - ID of the space in form of a string
    + hook_id: hook123 (required, string) - ID of the webhook in form of a string
    + call_id: A123FOO (required, string) - ID of the webhook call in form of a string

### Get the webhook call details [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json


+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Call Details)

## Webhook health [/spaces/{space_id}/webhooks/{hook_id}/health]

The health endpoint provides a simple overview of the amount of recently successful webhook calls

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string
    + hook_id: foobar (required, string) - ID of the Webhook in form of a string

### Get the webhook health [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Webhook Health)

# Group Roles

 Creating custom roles allows the admin to restrict access of users to certain resources. Roles are following a whitelisting approach, which means that everything that a user is allowed to do, needs to be explicitly defined. A role contains a name, a description, permissions and policies.

 Permissions on the one hand are basic rules which define whether or not a user can access content types, settings and entries. It can be specified if a user can read and/or manage those.

 On the other hand there are policies which can be used to allow or deny access to resources in a very fine-grained fashion. With polices you can for example limit read access to only entries of a specific content type or write access to only certain parts of an entry (e.g. for a specific locale).

 The following list explains the supported constraints:


- `and` - The AndConstraint evaluates if all its conditions are true. The value of the AndConstraint needs to be an array with an arbitrary amount of constraints.

  The AndConstraint is necessary and useful for a broad variety of use cases. An example for the constraint is the limitation to a specific content type:

  ```
  {"and": [
      { "equals": [{ "doc": "sys.type" }, "Entry"] },
      { "equals": [{ "doc": "sys.contentType.sys.id" }, "content-type-id"] }
  ]}
  ```

- `equals` - The EqualityConstraint can be used to compare an entity's field or meta data against a specific value.

  EqualityConstraints are one of the very basic constraints and are typically used to ensure the type of a document or to match entries of a content type. See the other use cases for examples.

- `not` - The NotConstraint inverts the result of its value.

  A typical use case for the NotConstraint is the inversion of whitelists to blacklist. If for example a user should not be able to see entries of a specific content type, it can either be achieved by denying access to those content types or by allowing access to all but the entries of the content type:

  ```
  {"and": [
      { "equals": [{ "doc": "sys.type" }, "Entry"] },
      { "not": { "equals": [{ "doc": "sys.contentType.sys.id" }, "content-type-id"] } }
  ]}
  ```

- `or` - The OrConstaint evaluates if one if its conditions returns true. The value of the OrConstraint needs to be an array with an arbitrary amount of constraints.

  OrConstraints can be used to enable an effect for various different resources. E.g. a user should only be allowed to read entries of a specific content type or all assets:

  ```
  {"or": [
      {"and": [
          { "equals": [{ "doc": "sys.type" }, "Entry"] },
          { "not": { "equals": [{ "doc": "sys.contentType.sys.id" }, "content-type-id"] } }
      ]},
      { "equals": [{ "doc": "sys.type" }, "Asset"] }
  ]}
  ```

## Roles collection [/spaces/{space_id}/roles]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the Space in form of a string

### Get all roles [GET]

This endpoint returns a paginated list of roles for a given space. Each role contains a name, a description, as well as permissions and policies, which describe what a user can and cannot do.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

### Create a role [POST]

This endpoint can be used to create a custom role. Please note that a role name must be unique within the space.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Role)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Role)

## Role [/spaces/{space_id}/roles/{role_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string
    + role_id: 1ElgCn1mi1UHSBLTP2v4TD (required, string) - ID of the role in a form of a string

### Get a single role [GET]

This endpoint can be used to read an existing single role.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

    + Attributes (Complete Role)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Role)

### Update a single role [PUT]

This endpoint can be used to update an existing role. Please note that this endpoint cannot be used to create a new role with a specific id.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Role)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Role)

### Delete a single role [DELETE]

This endpoint can be used to delete an existing role. The deletion of roles only possible if there is no user in the space which only has the soon-to-be-deleted role assigned.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 204

# Group Space memberships

## Space memberships collection [/spaces/{space_id}/space_memberships]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all space memberships [GET]

This endpoint returns a paginated list of all space memberships.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)

### Create a space membership [POST]

This endpoint allows the creation of a space membership (or in other words the invitation of a user to a space). A user can and must either be flagged as "admin" or assigned to certain roles.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Space Membership)

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Space Membership)

## Space membership [/spaces/{space_id}/space_memberships/{space_membership_id}]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in a form of a string
    + space_membership_id: 13ju26yx8X4xd6cNgrA5YA (required, string) - ID of the space membership in a form of a string

### Get a single space membership [GET]

The endpoint returns details about an existing space membership.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Space Membership)

### Update a single space membership [PUT]

The endpoints allows the modification of a space membership. This way additional roles can be assigned or a user can be flagged as an admin.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes (Space Membership)

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Complete Space Membership)

### Delete a single space membership [DELETE]

This endpoint allows the deletion of a space membership. It only affects the accessibility of space for user and not a user itself. Please note that it is possible to remove every administrator from a space. This means, there is no one left to manage the users. This can be fixed by inviting someone through the web application's organization settings.

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 204

# Group API keys

This endpoint allows the management of the Content Delivery API (CDA) keys. These tokens provide read-only access to a single space – that is, you need to obtain a new token for every new space that you want to access.

We recommend using different access tokens for different applications or delivery channels: for example, one for iOS app and another for Android app. One of the reasons is to be able to revoke them individually in the future: with several tokens you can manipulate your delivery channels independently.

## API keys collection [/spaces/{space_id}/api_keys]

+ Parameters
    + space_id: fp91oelsziea (required, string) - ID of the space in form of a string

### Get all API keys [GET]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1

+ Response 200 (application/vnd.contentful.management.v1+json)

    + Attributes (Empty Array)


### Create an API key [POST]

+ Request
    + Headers

            Authorization: Bearer b4c0n73n7fu1
            Content-Type: application/vnd.contentful.management.v1+json

    + Attributes
        - name: Example API Key - Name of the API Key

+ Response 201 (application/vnd.contentful.management.v1+json)

    + Attributes (API Key)


## Data Structures

### Asset

- Include Asset Update
- sys - System Attributes
    - id: baconpancakes - Identifier
    - type: Asset - Type of Resource
    - version: 1 (number) - Version of Resource
    - space (Space Link)
    - Include Resource Metadata

### Asset Published

- Include Asset
- Include Resource Published

### Asset Update

- fields - Field Values
    - title
        - `en-US`: Bacon Pancakes
    - file
        - `en-US`
            - contentType: image/jpeg
            - fileName: example.jpeg
            - upload: https://example.com/example.jpg

### Content Type

- sys
    - type: ContentType - Type of Resource
    - id: 3ORKIAOaJqQWWg86MWkyOs - Identifier
    - space (Space Link)
    - version: 1 (number) - Version of Resource
    - Include Resource Metadata

### Content Type Creation

- name: Blog Post - Name of the Content Type
- fields (array[object]) - Defined Fields
    - (object)
        - id: title - Identifier of the Field
        - name: Title - Display name of the Field
        - required: true (boolean)
        - localized: true (boolean)
        - type: Text - Type of the Field
    - (object)
        - id: body - Identifier of the Field
        - name: Body - Display name of the Field
        - required: true (boolean)
        - localized: true (boolean)
        - type: Text - Type of the Field

### Content Type Link
- sys
    - type: Link - Type of Resource
    - linkType: ContentType - Type of linked Resources
    - id: hfM9RCJIk0wIm06WkEOQY - Identifier of Resource

### Content Type Published

- Include Content Type Creation
- Include Content Type
- Include Resource Published

### Content Type Unpublished

- Include Content Type Creation
- Include Content Type
- sys - System Attributes
    - firstPublishedAt: `2015-05-15T13:38:11.311Z` - Date/Time of first publishing
    - publishedCounter: 2 (number) - Number of times the Resource has been published

### Content Type Update

- name: Blog Post - Name of the Content Type
- fields (array[object]) - Defined Fields
    - (object)
        - id: tlkn
- Include Content Type

### Content Type Update Field ID

- name: Blog Post - Name of the Content Type
- description: Simple blog post with headline and body fields. - Description of the Content Type
- fields (array[object]) - Defined Fields
    - (object)
        - id: title - Old identifier of the Field
        - newId: headline - New identifier of the Field
        - name: Headline - Display name of the Field
        - type: Text - Type of the Field
    - (object)
        - id: body - Identifier of the Field
        - name: Body - Display name of the Field
        - type: Text - Type of the Field

### Content Type Validations

- name: Blog Post - Name of the Content Type
- fields (array[object]) - Defined Fields
    - (object)
        - id: title - Identifier of the Field
        - name: Title - Display name of the Field
        - type: Text - Type of the Field
        - validations (array[object]) - Validations to be applied before publishing
            - (object)
                - size
                    min: 5
                - regexp
                    pattern: wow|very|such

### Empty Array

- sys - System Attributes
    - type: Array - Type of Resource
- total: 0 (number) - Total number of resources matching
- skip: 0 (number) - Number of resources skipped
- limit: 100 (number) - Maximum number of resources in this response
- items (array) - Resources contained in the array

### Entry

- Include Entry Update
- sys - System Attributes
    - id: helloworld - Identifier of Resource
    - type: Entry - Type of Resource
    - version: 1 (number) - Version of Resource
    - space (Space Link)
    - contentType (Content Type Link)
    - Include Resource Metadata

### Entry Published

- Include Entry
- Include Resource Published

### Entry Update

- fields - Localized field values
    - title
        - `en-US`: `Hello, World!`
    - body
        - `en-US`: Bacon is healthy!

### Locale

- name: `English (United States)` (string, required)
- code: `en-US` (string, required)
- optional: false (boolean) - Declare a locale as optional in localized fields

### Locale Complete

- Include Locale
- contentDeliveryApi: `true` (boolean)
- contentManagementApi: `true` (boolean)
- `default`: `false` (boolean)
- optional: `false` (boolean)
- sys - System Attributes
  - type: `Locale` (string)
  - id: `34N35DoyUQAtaKwWTgZs34` (string)
  - version: 0 (number)
  - space (Space Link)
  - Include Resource Metadata

### Resource Metadata

- createdAt: `2015-05-18T11:29:46.809Z` - Creation date
- createdBy (User B)
- updatedAt: `2015-05-18T11:29:46.809Z` - Date/time of last update
- updatedBy (User B)

### Resource Published

- sys - System Attributes
    - firstPublishedAt: `2015-05-15T13:38:11.311Z` - Date/time of first publishing
    - publishedCounter: 2 (number) - Number of times published
    - publishedAt: `2015-05-15T13:38:11.311Z` - Date/time of current publishing
    - publishedBy (User B)
    - publishedVersion: 9 (number) - Version of the resource that has been published

### Space

- sys - System Attributes
    - type: Space - Type of Resource
    - id: cfexampleapi - Identifier of Resource
    - version: 3 (number) - Version of Resource
    - Include Resource Metadata
- name: Contentful Example API - Name of Resource
- defaultLocale : en-US - Default locale of the Space

### Space Link
- sys - System Attributes
    - type: Link - Type of Resource
    - linkType: Space - Type of linked resources
    - id: fp91oelsziea - Identifier of Resource

### User A
- sys
    - type: Link
    - linkType: User
    - id: 7BslKh9TdKGOK41VmLDjFZ

### User B
- sys
    - type: Link
    - linkType: User
    - id: 4FLrUHftHW3v2BLi9fzfjU

### Webhook Definition

- sys - System Attributes
    - type: WebhookDefinition
    - id: foobar
    - version: 0 (number)
    - space (Space Link)
    - Include Resource Metadata
- name: My webhook (string, required)
- url: https://www.example.com (string, required)
- topics (array, required)
    - Entry.create
    - ContentType.create
    - *.publish
    - Asset.*
- httpBasicUsername: yolo (string)
- headers (array)
    - (object)
        - key: header1
        - value: value1
    - (object)
        - key: header2
        - value: value2

### Webhook attributes
  - name: My webhook (string, required) - Name of the Webhook
  - url: https://www.example.com/test (string, required) - URL the Webhook will call
  - topics: Entry.create, ContentType.create, *.publish, Asset.* (array, required) - List of topics you want to subscribe to with this webhook.  Every topic has to follow the Type.Action pattern and you can use * as a wildcard value for Type and Action.
  - httpBasicUsername: yolo (string) - Username for HTTP Basic Authentication
  - httpBasicPassword: yolo (string) - Password for HTTP Basic Authentication

### Webhook Call Overview

- sys
    - type: WebhookCallOverview (string)
    - id: bar (string)
    - space (Space Link)
    - createdBy
        - sys
            - type: Link
            - linkType: WebhookDefinition
            - id: foobar
    - createdAt: `2016-03-01T08:43:22.024Z` (string)
- statusCode: 200 (number) - The status code received from the endpoint
- errors (array[string]) - The error types if any
- eventType: publish - The type of event that triggered the webhook
- url: https://webhooks.example.com/endpoint (string) - URL the webhook was calling
- requestAt: `2016-03-01T08:43:22.024Z` (string) - The time the request was made
- responseAt: `2016-03-01T08:43:22.330Z` (string) - The time the response was received

### Webhook Call Overview Array

- sys - System Attributes
    - type: Array - Type of Resource
- total: 0 (number) - Total number of overviews matching
- skip: 0 (number) - Number of overviews skipped
- limit: 100 (number) - Maximum number of overviews in this response
- items (array[Webhook Call Overview]) - List of overviews


### Webhook Call Details

- sys
    - type: WebhookCallDetails (string)
    - id: bar (string)
    - space (Space Link)
    - createdBy
        - sys
            - type: Link
            - linkType: WebhookDefinition
            - id: foobar
    - createdAt: `2016-03-01T08:43:22.024Z` (string)
- request (object) - The webhook request sent to the specified endpoint
    - url: https://webhooks.example.com/endpoint (string) - URL the POST was sent to
    - method: POST (string)
    - headers
        - `X-Contentful-Topic`: ContentManagement.Entry.publish (string) - The corresponding topic header
        - `Content-Type`: application/vnd.contentful.management.v1+json (string)
    - body: {} (string) - The body of the webhook request
- response (object) - The response received from the endpoint
    - url: https://webhooks.example.com/endpoint (string) - URL the response came from
    - headers
        - `Content-Type`: `text/html; charset=utf-8` (string)
        - `Content-Length`: 2 (string)
    - body: ok (string) - The body of the response
    - statusCode: 200 (number) - The status code received from the endpoint
- statusCode: 200 (number) - The status code received from the endpoint
- errors (array[string]) - The error types if any
- eventType: publish - The type of event that triggered the webhook
- url: https://webhooks.example.com/endpoint (string) - URL the webhook was calling
- requestAt: `2016-03-01T08:43:22.024Z` (string) - The time the request was made
- responseAt: `2016-03-01T08:43:22.330Z` (string) - The time the response was received

### Webhook Health

- sys
    - type: Webhook (string)
    - id: bar (string)
    - space (Space Link)
    - createdBy
        - sys
            - type: Link
            - linkType: WebhookDefinition
            - id: foobar
- calls (object) - The health data
    - total: 233 (number) - Total amount of calls used as a Reference
    - healthy: 102 (number) - The amount of responses with a non 2xx status code

### API Key

- sys - System Attributes
    - type: ApiKey
    - id: exampleapikey - Identifier of Resource
    - version: 0 (number) - Version of Resource
    - Include Resource Metadata
- name: Example API Key - Name of Resource

### Role

- name: Some role (string, required) - Name of Resource
- description: Test role (string) - Description of Resource
- permissions - Permissions for accessing application sections
    - ContentDelivery: all (string)
    - ContentModel (array[string])
        - read
    - Settings (array[string])
        - read
        - manage
- policies (array[Policy]) - Custom policies

### Complete Role

- sys - System Attributes
    - type: Role (string)
    - id: 34SHqvY4zjISqXNawkyTwq - Identifier of Resource
    - version: 0 (number) - Version of Resource
    - Include Resource Metadata
- Include Role

### Policy

- effect: allow (string) - Allow or deny an action
- actions (array[string]) - Array of strings or "all" string shortcut
    - read
    - create
    - update
    - delete
    - publish
    - unpublish
    - archive
    - unarchive
- constraint
    - equals (array)
        - doc
            - doc: sys.type (string)
        - Entry (string)

### Space Membership

- admin: false (boolean) - Flag indicating if user is an administrator
- roles (array[RoleLink]) - Array of Role links

### Complete Space Membership

- sys - System Attributes
    - type: SpaceMembership (string)
    - id: 13ju26yx8X4xd6cNgrA5YA - Identifier of Resource
    - version: 0 (number) - Version of Resource
    - Include Resource Metadata
- Include Space Membership

### RoleLink

- type: Link (string)
- linkType: Role (string)
- id: 1ElgCn1mi1UHSBLTP2v4TD (string)

:[Data Structures](_partials/cma/data-structures.apib)
