## Preview API Authentication

You authenticate with the Preview API in the same way as the Delivery API, but using a Preview access token.

Your production Delivery API access tokens will not work with the Preview API. The use of a separate token helps prevent accidentally leaking unpublished content. Every Delivery API key has an associated preview access token, which you can view in the "API" tab of the Contentful app.

## Using the Preview API

You use the Preview API as though it were the Delivery API, but replacing the hostname `cdn.contentful.com` with `preview.contentful.com`, and the production access token with a preview access token.

## Preview API Limitations

The Preview API does not implement the Sync API, so applications that rely exclusively on the Sync API to load data will not be usable with the Preview API.
