FORMAT: 1A
HOST: https://preview.contentful.com

# Content Preview API

In addition to the Delivery API for published content, there is also a Preview API for previewing unpublished content as though it were published. It maintains the same behaviour and parameters as the Content Delivery API, but delivers the latest draft for entries and assets.
