FORMAT: 1A
HOST: https://preview.contentful.com

# Preview API

In addition to the Content Delivery API for published content, there is also a Preview API for previewing unpublished content as though it were published. It maintains the same behaviour and parameters as the Content Delivery API, but delivers the latest draft for entries and assets.

## Preview API authentication

You authenticate with the Preview API in the same way as the Content Delivery API, but using a preview access token.

Your production access tokens will not work with the Preview API. The use of a separate token helps prevent accidentally leaking unpublished content. Every delivery API key has an associated preview access token, which you can view in the "APIs" tab in the Contentful web app.

## Using the Preview API

You use the Preview API as though it were the Content Delivery API, but replacing the hostname `cdn.contentful.com` with `preview.contentful.com`, and the production access token with a preview access token.

## Preview API limitations

The Preview API does not implement the Sync API, so applications that rely exclusively on the Sync API to load data will not be usable with the Preview API.

## API rate limits

The Content Preview API enforces standard rate limits per hour and per second. The limits exist to prevent unlimited usage and ensure the consumption of resources that a single account can exercise is limited. Rate limits are set to 7200 requests per hour and 10 requests per second.

The rate limits are implemented through a standard mechanism of the HTTP protocol (returning response code 429).

The Content Preview API uses the `X-Contentful-RateLimit-Reset` header to inform a user when they can make their next request. This header is only sent for rate limited requests (429). The rate limiting headers used in the Content Preview API are identical to those of the Content Delivery API for compatibility reasons.

Header                            | Status Code                                       | Description
----------------------------------|---------------------------------------------------|----------------------------------------------------
`X-Contentful-RateLimit-Reset`    | `429`. Returned only for rate limited requests.   | The number of seconds until the next request can be made.

It's important to note that the `X-Contentful-RateLimit-Reset` header does _not_ return the time until the next full reset. Instead it tells you when the next request can be made. If a per second rate limit is enforced it will return `1` (time until the next second). If an hourly rate limit is enforced it will return the time until the next sliding window.

:[Common Resource Attributes](_partials/cda/resource-attributes.apib apiname:"Preview API")

:[Shared Preview/Delivery Docs](_partials/delivery-and-preview-resources.apib tokentype:"A *preview* Content Delivery API key.")

:[Data Structures](_partials/delivery-and-preview-data-structures.apib)
